// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgpjrsjprbhixonkhujf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndncGpyc2pwcmJoaXhvbmtodWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NjY0NDAsImV4cCI6MjA4ODA0MjQ0MH0.dxUODwqmbza39Z3N0Eb-8EpI6TiZYtXsyQzAjvFoXp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});